skips thread safety test
```
more_core_extensions/spec/core_ext/module/cache_with_timeout_spec.rb:168:in
`block (5 levels) in <top (required)>': undefined method `thread_safety' for

          test_class.thread_safety(true)
                    ^^^^^^^^^^^^^^
	from more_core_extensions/spec/core_ext/module/cache_with_timeout_spec.rb:167:in
	    `times'
	from more_core_extensions/spec/core_ext/module/cache_with_timeout_spec.rb:167:in
	    `block (4 levels) in <top (required)>'
```